export const mockstate = {
  minefield: {
    mines: [
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'CLOSED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'FLAGGED' },
      { state: 'CLOSED', content: 'EMPTY' },
      { state: 'CLOSED', content: 'MINE' },
      { state: 'CLOSED', content: '1' },
      { state: 'CLOSED', content: '2' },
      { state: 'CLOSED', content: '3' },
      { state: 'CLOSED', content: '4' },
      { state: 'CLOSED', content: '5' },
      { state: 'CLOSED', content: '6' },
      { state: 'CLOSED', content: '7' },
      { state: 'CLOSED', content: '8' },
      { state: 'FLAGGED', content: 'EMPTY' },
      { state: 'FLAGGED', content: 'MINE' },
      { state: 'FLAGGED', content: '1' },
      { state: 'FLAGGED', content: '2' },
      { state: 'FLAGGED', content: '3' },
      { state: 'FLAGGED', content: '4' },
      { state: 'FLAGGED', content: '5' },
      { state: 'FLAGGED', content: '6' },
      { state: 'FLAGGED', content: '7' },
      { state: 'FLAGGED', content: '8' },
      { state: 'OPEN', content: 'EMPTY' },
      { state: 'OPEN', content: 'MINE' },
      { state: 'OPEN', content: '1' },
      { state: 'OPEN', content: '2' },
      { state: 'OPEN', content: '3' },
      { state: 'OPEN', content: '4' },
      { state: 'OPEN', content: '5' },
      { state: 'OPEN', content: '6' },
      { state: 'OPEN', content: '7' },
      { state: 'OPEN', content: '8' },
    ],
    cols: 10
  }
}